### ISSUE TITLE
Dropping `conda_build_config.yaml`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/seekr2_openmm_plugin-feedstock#13]
It looks like there is a custom `conda_build_config.yaml`

https://github.com/conda-forge/seekr2_openmm_plugin-feedstock/blob/e4011600566bf78df010dbce85315f9b62bdeb51/recipe/conda_build_config.yaml#L1-L10

Mentioning this as it [confused one of the migrators recently]( https://github.com/regro/cf-scripts/actions/runs/6963632203/job/18949562094#step:9:5517 ). This could potentially impact other migrators and version updates from the bot

Am wondering if there is another approach we can apply here to accomplish the same goal. Could you please share a bit more about what problem the custom `conda_build_config.yaml` is solving? Maybe we can come with a better approach together

**Comment by lvotapka** [comment]
Hi @jakirkham, thanks for reaching out. I've had a tremendous amount of difficulty combining conda-forge with builds that use CUDA, and many of my users spent enormous amounts of time struggling to install seekr2_openmm_plugin using conda-forge on certain OSs. The problem seems to be solved if only CUDA 10.2 is used (not CUDA 11). So this file specifies the versions of CUDA and other compilers that don't cause installation issues for me or my users. I'm open to suggestions for solving this problem, and for avoiding the problems with the migrators you mentioned.

**Comment by jakirkham** [comment]
Thanks for your reply Lane! 🙏

Could you please share some more details about the issues users ran into? Like what did they try, what errors did they see, how are their systems configured, etc.?

**Comment by lvotapka** [comment]
Yes, I'd be glad to. The seekr2_openmm_plugin is a SWIG-based Python module, that can be imported. But users were unable to import the module properly: it would give a ModuleNotFoundError.

This was annoying because "conda list" showed "seekr2_openmm_plugin" as installed just fine.

Whereas, on other machines, everything seemed to work fine. Upon further investigation, I determined that the "conda install" command never put the seekr2_openmm_plugin files into the lib/python3.8/site-packages/ directory of the conda environment - the files are just missing, even tho conda thinks that seekr2_openmm_plugin is installed.

After significant amounts of trial and error, I determined that the problem only occurred if CUDA 11 was being used (CUDA 10 worked fine). I scoured the Azure pipeline log files for hints about what error was occurring that prevented conda-forge from being able to correctly use CUDA 11, but no clear errors or warnings gave me enough of a hint to fix the problem with CUDA 11. So I just decided to fall back and require CUDA 10 - not a good long-term solution, but it at least allowed the users to get past the problem temporarily.

So how would you like to proceed? Should I recreate the error with the CUDA 11 compiles so you can see the problem I'm referring to?

**Comment by jakirkham** [comment]
Thanks for sharing Lane! 🙏

Interesting that certainly is not an error I would have anticipated

Yeah am curious to see how this reproduces. Think one way we could proceed is

1. Create a (draft) PR that deletes `conda_build_config.yaml`
2. Enable [`azure/store_build_artifacts`]( https://conda-forge.org/docs/maintainer/conda_forge_yml.html#azure ) in `conda-forge.yml`
3. [Re-render]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#dev-update-rerender )

That should build packages for CUDA 11.2 and cache them on CI. Additionally there are...

* Some [docs on downloading artifacts from CI]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#downloading-prebuilt-packages-from-ci )
* Some examples with screenshots in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1424 )

This should give us a low stakes way of confirming a reproducer with a known set of changes that we can work on together

What do you think about this proposal? 🙂

**Comment by lvotapka** [comment]
I like this proposal, @jakirkham. I finished implementing the first 3 steps of your suggestion, and your instructions for downloading them are thorough. However, I think I must be missing something because I don't see the ability to download the artifacts from the CI. It just shows the line that says "9 queue time variables used" like in your screenshot, but there's no option saying "# artifacts produced". I have the following lines in my conda-forge.yml file:

```
azure:
  store_build_artifacts: true
```
Have I set up any of the options incorrectly to download artifacts?
